### ISSUE TITLE
requirements.txt file with dependencies

### ISSUE THREAD

**Issue by MeltedHyperion7** [popelier-group/ichor#62]
The project is missing a `requirements.txt` listing all the dependencies needed to run tests, ichor-CLI, and build documentation.

It should be straightforward to create the file using,
```bash
pip freeze > requirements.txt
```

**Comment by m-julian** [comment]
Thanks, yes it is missing a `requirements.txt`. However, for big projects like this it is better to have `setup.py`/`setup.cfg` which contain the required dependencies that are installed when doing `pip install ichor_core` for example. That way dependencies only have to be updated in one place instead of two. Here is an example https://github.com/popelier-group/ichor/blob/main/ichor_core/setup.cfg.
